apiVersion: apps/v1
kind: Deployment
metadata:
    name: aiohttp
spec:
    selector:
        matchLabels:
            app: aiohttp
    template:
        metadata:
            labels:
                app: aiohttp
        spec:
            containers:
            - image: chaowenguo/aiohttp:latest
              name: aiohttp
---
apiVersion: v1
kind: Service
metadata:
    name: aiohttp
    annotations:
        dev.okteto.com/auto-ingress: 'true'
spec:
    selector:
        app: aiohttp
    ports:
    - port: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim        # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                          # Claim name and labels
    name: postgres-pv-claim
spec:                              # Access mode and resource limits
    accessModes:
    - ReadWriteOnce                # ReadWriteOnce means the volume can be mounted as read-write by a single Node
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
spec:
    selector:
        matchLabels: 
            app: postgres
    template: 
        metadata:
            labels:  
                app: postgres
        spec: 
            containers:
            - image: chaowenguo/postgres:latest
              name: postgres
              volumeMounts:
              - name: postgres-persistent-storage
                mountPath: /var/lib/postgresql/data
                subPath: postgres
            volumes:
            - name: postgres-persistent-storage
              persistentVolumeClaim:
                  claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
    name: postgres
spec:
    selector:
        app: postgres
    ports:
    - port: 5432
