on:
    push:
    schedule:
    - cron: '*/5 * * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@master
        - uses: actions/setup-python@master
          with:
              python-version: '3.x'
        - run: |
              pip install aiohttp
              python build.py ${{secrets.GITHUB}}
        - uses: docker/login-action@master
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@master
        - uses: docker/build-push-action@master
          with:
              push: true
              tags: chaowenguo/aiohttp:latest
        - uses: docker/build-push-action@master
          with:
              push: true
              context: database
              file: database/Dockerfile
              tags: chaowenguo/postgres:latest
        - uses: docker/build-push-action@master
          with:
              push: true
              context: chat
              file: chat/Dockerfile
              tags: chaowenguo/chat:latest
        - uses: okteto/login@master
          with:
              token: ${{secrets.OKTETO}}
        - uses: okteto/namespace@master
          with:
              namespace: chaowenguo
        - uses: okteto/apply@master
          with:
              manifest: k8s.yml
    call:
        runs-on: ubuntu-latest
        steps:
        - run: 
              curl https://aiohttp-chaowenguo.cloud.okteto.net
