on:
    push:
    schedule:
    - cron: '0 6,18 * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-python@main
          with:
              python-version: '3.x'
        - run: |
              pip install aiohttp
              python build.py ${{secrets.GITHUB}}
        - uses: docker/login-action@main
          with:
              username: chaowenguo
              password: ${{secrets.DOCKER}}
        - uses: docker/setup-buildx-action@main
        - uses: docker/build-push-action@main
          with:
              push: true
              tags: chaowenguo/aiohttp:latest
        - uses: docker/build-push-action@main
          with:
              push: true
              context: database
              file: database/Dockerfile
              tags: chaowenguo/postgres:latest
        - uses: docker/build-push-action@main
          with:
              push: true
              context: chat
              file: chat/Dockerfile
              tags: chaowenguo/chat:latest
        - uses: okteto/login@master
          with:
              token: ${{secrets.OKTETO}}
        - uses: okteto/namespace@master
          with:
              namespace: chaowenguo
        - uses: okteto/apply@master
          with:
              manifest: k8s.yml
        - run: sudo kubectl --kubeconfig=$RUNNER_TEMP/_github_home/.kube/config rollout restart deploy aiohttp
